name: Terraform Destroy Workflow with Domain

on:
  workflow_dispatch:
    inputs:
      domain:
        description: "The domain name to destroy the Terraform infrastructure for"
        required: true
        type: string
      target_environment:
        description: "The environment in which to destroy"
        required: true
        type: choice
        options:
          - "alex"
          - "matt"
          - "deliberately bogus"
        default: "deliberately bogus"

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.target_environment }}    

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-oidc/github-deployment

      - name: Initialize Terraform
        run: |
          terraform init \
            -backend-config="bucket=tf-state-eu-west-2-${{ secrets.AWS_ACCOUNT_ID }}" \
            -backend-config="region=eu-west-2" \
            -backend-config="key=ClickyMcSiteFace/${{ github.event.inputs.domain }}.tfstate"

      - name: Terraform Plan for Destroy
        run: |
          terraform plan -destroy -out=tfplan \
            -var "domain=${{ github.event.inputs.domain }}" \
            -var "template=place/holder"

      - name: Terraform Destroy
        run: |
          terraform apply -auto-approve tfplan
